# Project
version=1.2.0
group=com.github.phylogeny.bettercushionplacement
java_version=25

# Common
minecraft_version=26.3-snapshot-5
mod_name=BetterCushionPlacement
mod_display_name=Better Cushion Placement
mod_author=Phylogeny
mod_id=bettercushionplacement
license=CC0-1.0
credits=
description=modmenu.descriptionTranslation.bettercushionplacement
logo=assets/bettercushionplacement/logo.png
curseforge_homepage_url=https://curseforge.com/minecraft/mc-mods/better-cushion-placement
curseforge_update_url=https://curseupdate.com/1608419/better-cushion-placement?ml=neoforge
modrinth_homepage_url=https://modrinth.com/mod/better-cushion-placement
modrinth_update_url=https://api.modrinth.com/updates/better-cushion-placement/forge_updates.json?neoforge=only
source_url=https://github.com/Phylogeny/BetterCushionPlacement
issue_tracker_url=https://github.com/Phylogeny/BetterCushionPlacement/issues
minecraft_version_range=[26.3, 26.4)

# NeoForm: https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-snapshot-5-1

# Common
toml4j_version=0.7.2
configurate_version=4.2.0
geantyref_version=1.3.16
kyori_option_version=1.1.0

# Fabric: https://fabricmc.net/develop/
fabric_version=0.155.3+26.3
fabric_loader_version=0.19.3
modmenu_version=21.0.0-alpha.1
yacl_fabric_version=3.9.6+26.3-fabric

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)
yacl_neoforge_version=3.9.6+26.2-neoforge

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
